In [1]:
import pandas as pd

In [2]:
from matplotlib import pyplot as plt

In [3]:
front_page_data = pd.read_csv('alltables.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'alltables.csv'

In [4]:
front_page_data = pd.read_csv('Alltables.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Alltables.csv'

In [5]:
front_page_data = pd.read_csv('Alltables.csv')

In [6]:
front_page_data

,Summary data on annual food imports value and volume by food category and source country 1999-2017,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42
0,NaN,Food group,NaN,1999,2000,2001,2002,2003,2004,2005,...,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,NaN,Avg.growth
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-17
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Total U.S. food imports 1/,NaN,NaN,"43,105.8","45,416.5","46,063.1","49,209.3","55,328.9","61,531.4","67,803.6",...,12.4,17.8,3.9,2.9,8.9,1.3,1.8,6.3,NaN,5.9
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Live meat animals,NaN,NaN,"1,189.7","1,419.0","1,771.2","1,723.9","1,276.7","1,134.3","1,672.0",...,21.2,-6.0,16.2,-0.1,37.4,-7.8,-24.2,-3.9,NaN,1.1
6,Meats,NaN,NaN,"3,260.5","3,827.7","4,256.2","4,283.5","4,426.8","5,718.5","5,751.9",...,10.3,13.1,8.5,4.6,36.9,11.8,-14.0,3.4,NaN,5.7
7,Fish and shellfish 2/,NaN,NaN,"8,859.8","9,879.8","9,663.3","9,963.3","10,859.9","11,106.3","11,840.2",...,12.2,13.4,0.0,8.0,12.8,-7.6,4.0,10.7,NaN,4.8
8,Dairy,NaN,NaN,930.3,922.3,995.8,"1,008.8","1,110.3","1,292.3","1,388.4",...,-0.5,11.5,6.8,2.8,11.8,2.7,-0.9,-2.6,NaN,2.7
9,Vegetables,NaN,NaN,"3,631.6","3,771.4","4,156.6","4,391.1","5,082.4","5,730.0","6,043.1",...,15.7,11.0,2.9,7.9,1.8,3.3,10.4,2.2,NaN,6.3
10,Fruits,NaN,NaN,"4,764.5","4,629.5","4,665.2","5,067.6","5,557.7","5,962.4","6,873.8",...,10.5,12.4,4.7,8.5,8.9,7.7,7.5,7.1,NaN,8.3
11,Nuts,NaN,NaN,793.9,808.7,670.2,700.5,775.6,"1,078.4","1,121.9",...,14.3,27.5,7.3,0.0,18.0,17.2,3.7,15.0,NaN,10.9
12,"Coffee, tea, and spices",NaN,NaN,"3,603.7","3,441.8","2,400.7","2,455.0","2,871.9","3,144.3","3,770.8",...,21.4,55.1,-10.2,-12.5,8.7,2.9,-2.6,9.1,NaN,8.6
13,Grains,NaN,NaN,"2,659.5","2,734.8","2,989.8","3,342.8","3,618.2","4,010.5","4,240.7",...,4.3,13.0,13.0,12.6,-2.2,0.0,1.5,6.7,NaN,8.0
14,Vegetable oils,NaN,NaN,"1,356.9","1,362.5","1,177.0","1,301.6","1,506.5","2,241.0","2,362.6",...,11.6,50.7,-8.2,6.9,10.1,-14.1,3.5,10.8,NaN,11.7
15,Sugar and candy,NaN,NaN,"1,617.7","1,571.6","1,580.9","1,842.6","2,130.8","2,111.3","2,473.7",...,33.3,26.8,-8.1,-9.5,5.9,2.7,-0.3,0.6,NaN,5.0
16,Cocoa and chocolate,NaN,NaN,"1,522.5","1,404.5","1,535.9","1,760.9","2,439.2","2,484.4","2,750.6",...,23.6,9.0,-12.5,1.5,13.7,2.8,4.5,-1.5,NaN,6.4
17,Other edible products,NaN,NaN,"2,121.5","2,101.7","2,252.0","2,482.0","3,637.2","4,784.4","5,536.4",...,11.0,19.9,35.0,-10.4,-1.2,-1.3,-2.5,8.4,NaN,5.7
18,Beverages 3/,NaN,NaN,"4,411.8","4,815.9","5,101.3","5,794.7","6,597.5","7,024.3","7,887.5",...,6.2,9.5,7.1,3.6,6.4,6.9,5.5,6.6,NaN,4.3
19,Liquors,NaN,NaN,"2,381.9","2,725.5","2,847.0","3,091.1","3,438.2","3,709.2","4,089.9",...,8.4,10.5,5.0,6.1,3.1,2.8,5.8,2.8,NaN,4.7
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Food totals 4/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Total animal foods,NaN,NaN,"14,240.3","16,048.8","16,686.4","16,979.5","17,673.7","19,251.3","20,652.6",...,11.7,11.5,3.5,6.2,20.2,-2.0,-4.1,7.0,NaN,4.4
23,Total plant foods,NaN,NaN,"22,071.8","21,826.3","21,428.4","23,344.0","27,619.5","31,546.6","35,173.6",...,14.3,22.6,3.5,1.2,5.2,1.7,3.5,6.3,NaN,7.2
24,Total beverages,NaN,NaN,"6,793.7","7,541.4","7,948.3","8,885.8","10,035.7","10,733.5","11,977.4",...,7.0,9.9,6.3,4.5,5.2,5.4,5.6,5.3,NaN,4.4
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"1/ Values are obtained by HS-4 or 6 codes, by ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,"See Appendix for the HS-2, HS-4, and HS-6 cod...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,4 / Excludes items not in total U.S. food impo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,"Source: USDA, www.fas.usda.gov/gats.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
front_page_data = pd.read_csv('Alltables.csv')

In [8]:
front_page_data

,Summary data on annual food imports value and volume by food category and source country 1999-2017,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42
0,NaN,Food group,NaN,1999,2000,2001,2002,2003,2004,2005,...,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,NaN,Avg.growth
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-17
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Total U.S. food imports 1/,NaN,NaN,"43,105.8","45,416.5","46,063.1","49,209.3","55,328.9","61,531.4","67,803.6",...,12.4,17.8,3.9,2.9,8.9,1.3,1.8,6.3,NaN,5.9
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Live meat animals,NaN,NaN,"1,189.7","1,419.0","1,771.2","1,723.9","1,276.7","1,134.3","1,672.0",...,21.2,-6.0,16.2,-0.1,37.4,-7.8,-24.2,-3.9,NaN,1.1
6,Meats,NaN,NaN,"3,260.5","3,827.7","4,256.2","4,283.5","4,426.8","5,718.5","5,751.9",...,10.3,13.1,8.5,4.6,36.9,11.8,-14.0,3.4,NaN,5.7
7,Fish and shellfish 2/,NaN,NaN,"8,859.8","9,879.8","9,663.3","9,963.3","10,859.9","11,106.3","11,840.2",...,12.2,13.4,0.0,8.0,12.8,-7.6,4.0,10.7,NaN,4.8
8,Dairy,NaN,NaN,930.3,922.3,995.8,"1,008.8","1,110.3","1,292.3","1,388.4",...,-0.5,11.5,6.8,2.8,11.8,2.7,-0.9,-2.6,NaN,2.7
9,Vegetables,NaN,NaN,"3,631.6","3,771.4","4,156.6","4,391.1","5,082.4","5,730.0","6,043.1",...,15.7,11.0,2.9,7.9,1.8,3.3,10.4,2.2,NaN,6.3
10,Fruits,NaN,NaN,"4,764.5","4,629.5","4,665.2","5,067.6","5,557.7","5,962.4","6,873.8",...,10.5,12.4,4.7,8.5,8.9,7.7,7.5,7.1,NaN,8.3
11,Nuts,NaN,NaN,793.9,808.7,670.2,700.5,775.6,"1,078.4","1,121.9",...,14.3,27.5,7.3,0.0,18.0,17.2,3.7,15.0,NaN,10.9
12,"Coffee, tea, and spices",NaN,NaN,"3,603.7","3,441.8","2,400.7","2,455.0","2,871.9","3,144.3","3,770.8",...,21.4,55.1,-10.2,-12.5,8.7,2.9,-2.6,9.1,NaN,8.6
13,Grains,NaN,NaN,"2,659.5","2,734.8","2,989.8","3,342.8","3,618.2","4,010.5","4,240.7",...,4.3,13.0,13.0,12.6,-2.2,0.0,1.5,6.7,NaN,8.0
14,Vegetable oils,NaN,NaN,"1,356.9","1,362.5","1,177.0","1,301.6","1,506.5","2,241.0","2,362.6",...,11.6,50.7,-8.2,6.9,10.1,-14.1,3.5,10.8,NaN,11.7
15,Sugar and candy,NaN,NaN,"1,617.7","1,571.6","1,580.9","1,842.6","2,130.8","2,111.3","2,473.7",...,33.3,26.8,-8.1,-9.5,5.9,2.7,-0.3,0.6,NaN,5.0
16,Cocoa and chocolate,NaN,NaN,"1,522.5","1,404.5","1,535.9","1,760.9","2,439.2","2,484.4","2,750.6",...,23.6,9.0,-12.5,1.5,13.7,2.8,4.5,-1.5,NaN,6.4
17,Other edible products,NaN,NaN,"2,121.5","2,101.7","2,252.0","2,482.0","3,637.2","4,784.4","5,536.4",...,11.0,19.9,35.0,-10.4,-1.2,-1.3,-2.5,8.4,NaN,5.7
18,Beverages 3/,NaN,NaN,"4,411.8","4,815.9","5,101.3","5,794.7","6,597.5","7,024.3","7,887.5",...,6.2,9.5,7.1,3.6,6.4,6.9,5.5,6.6,NaN,4.3
19,Liquors,NaN,NaN,"2,381.9","2,725.5","2,847.0","3,091.1","3,438.2","3,709.2","4,089.9",...,8.4,10.5,5.0,6.1,3.1,2.8,5.8,2.8,NaN,4.7
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Food totals 4/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Total animal foods,NaN,NaN,"14,240.3","16,048.8","16,686.4","16,979.5","17,673.7","19,251.3","20,652.6",...,11.7,11.5,3.5,6.2,20.2,-2.0,-4.1,7.0,NaN,4.4
23,Total plant foods,NaN,NaN,"22,071.8","21,826.3","21,428.4","23,344.0","27,619.5","31,546.6","35,173.6",...,14.3,22.6,3.5,1.2,5.2,1.7,3.5,6.3,NaN,7.2
24,Total beverages,NaN,NaN,"6,793.7","7,541.4","7,948.3","8,885.8","10,035.7","10,733.5","11,977.4",...,7.0,9.9,6.3,4.5,5.2,5.4,5.6,5.3,NaN,4.4
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"1/ Values are obtained by HS-4 or 6 codes, by ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,"See Appendix for the HS-2, HS-4, and HS-6 cod...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,4 / Excludes items not in total U.S. food impo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,"Source: USDA, www.fas.usda.gov/gats.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
front_page_data = pd.read_csv('Alltables.csv')

In [10]:
front_page_data

,Summary data on annual food imports value and volume by food category and source country 1999-2017,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40
0,NaN,1999.0,2000.0,2001.0,2002.0,2003.0,2004.0,2005.0,2006,2007.0,...,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,NaN,Avg.growth
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Million $,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-17
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Total U.S. food imports 1/,43105.8,45416.5,46063.1,49209.3,55328.9,61531.4,67803.6,74649.9,81076.2,...,12.4,17.8,3.9,2.9,8.9,1.3,1.8,6.3,NaN,5.9
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Live meat animals,1189.7,1419.0,1771.2,1723.9,1276.7,1134.3,1672.0,2172,2588.0,...,21.2,-6.0,16.2,-0.1,37.4,-7.8,-24.2,-3.9,NaN,1.1
6,Meats,3260.5,3827.7,4256.2,4283.5,4426.8,5718.5,5751.9,5243.6,5367.3,...,10.3,13.1,8.5,4.6,36.9,11.8,-14.0,3.4,NaN,5.7
7,Fish and shellfish 2/,8859.8,9879.8,9663.3,9963.3,10859.9,11106.3,11840.2,13112.3,13434.6,...,12.2,13.4,0.0,8.0,12.8,-7.6,4.0,10.7,NaN,4.8
8,Dairy,930.3,922.3,995.8,1008.8,1110.3,1292.3,1388.4,1405.7,1500.8,...,-0.5,11.5,6.8,2.8,11.8,2.7,-0.9,-2.6,NaN,2.7
9,Vegetables,3631.6,3771.4,4156.6,4391.1,5082.4,5730.0,6043.1,6619.3,7256.0,...,15.7,11.0,2.9,7.9,1.8,3.3,10.4,2.2,NaN,6.3
10,Fruits,4764.5,4629.5,4665.2,5067.6,5557.7,5962.4,6873.8,7707.1,9217.3,...,10.5,12.4,4.7,8.5,8.9,7.7,7.5,7.1,NaN,8.3
11,Nuts,793.9,808.7,670.2,700.5,775.6,1078.4,1121.9,1099.4,1181.4,...,14.3,27.5,7.3,0.0,18.0,17.2,3.7,15.0,NaN,10.9
12,"Coffee, tea, and spices",3603.7,3441.8,2400.7,2455.0,2871.9,3144.3,3770.8,4194.9,4791.2,...,21.4,55.1,-10.2,-12.5,8.7,2.9,-2.6,9.1,NaN,8.6
13,Grains,2659.5,2734.8,2989.8,3342.8,3618.2,4010.5,4240.7,4910.1,5914.8,...,4.3,13.0,13.0,12.6,-2.2,0.0,1.5,6.7,NaN,8
14,Vegetable oils,1356.9,1362.5,1177.0,1301.6,1506.5,2241.0,2362.6,2818.3,3516.7,...,11.6,50.7,-8.2,6.9,10.1,-14.1,3.5,10.8,NaN,11.7
15,Sugar and candy,1617.7,1571.6,1580.9,1842.6,2130.8,2111.3,2473.7,3021.2,2606.2,...,33.3,26.8,-8.1,-9.5,5.9,2.7,-0.3,0.6,NaN,5
16,Cocoa and chocolate,1522.5,1404.5,1535.9,1760.9,2439.2,2484.4,2750.6,2659.2,2661.6,...,23.6,9.0,-12.5,1.5,13.7,2.8,4.5,-1.5,NaN,6.4
17,Other edible products,2121.5,2101.7,2252.0,2482.0,3637.2,4784.4,5536.4,5963.1,6080.0,...,11.0,19.9,35.0,-10.4,-1.2,-1.3,-2.5,8.4,NaN,5.7
18,Beverages 3/,4411.8,4815.9,5101.3,5794.7,6597.5,7024.3,7887.5,9212.1,9912.7,...,6.2,9.5,7.1,3.6,6.4,6.9,5.5,6.6,NaN,4.3
19,Liquors,2381.9,2725.5,2847.0,3091.1,3438.2,3709.2,4089.9,4511.5,5047.7,...,8.4,10.5,5.0,6.1,3.1,2.8,5.8,2.8,NaN,4.7
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Food totals 4/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Total animal foods,14240.3,16048.8,16686.4,16979.5,17673.7,19251.3,20652.6,21933.6,22890.7,...,11.7,11.5,3.5,6.2,20.2,-2.0,-4.1,7.0,NaN,4.4
23,Total plant foods,22071.8,21826.3,21428.4,23344.0,27619.5,31546.6,35173.6,38992.6,43225.2,...,14.3,22.6,3.5,1.2,5.2,1.7,3.5,6.3,NaN,7.2
24,Total beverages,6793.7,7541.4,7948.3,8885.8,10035.7,10733.5,11977.4,13723.6,14960.4,...,7.0,9.9,6.3,4.5,5.2,5.4,5.6,5.3,NaN,4.4
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"1/ Values are obtained by HS-4 or 6 codes, by ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,"See Appendix for the HS-2, HS-4, and HS-6 cod...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,4 / Excludes items not in total U.S. food impo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,"Source: USDA, www.fas.usda.gov/gats.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN